plugins:
  shadowban_enabled:
    default: true
    client: true
  shadowban_users:
    default: ""
    client: false
  shadowban_show_to_staff:
    default: false
    client: true
  shadowban_posts:
    default: true
    client: true
